### ISSUE TITLE
The SR-IOV network card cannot communicate under PVE

### ISSUE THREAD

**Issue by canghaiwuhen** [jpetazzo/pipework#258]
PC：AMD 5800U
System：Proxmox VE 8
NetCard：Intel X710 -> SR-IOV to 8 VF -> VF1[vlan81] / VF2[vlan82]
vlan81:192.168.81.x
vlan82:192.168.82.x

---
VirtualPC：Ubuntu 20.04
NetCard1: VF1 -> 192.168.81.10
NetCard2: VF2 -> 192.168.82.10

cat /etc/netplan/00-installer-config.yaml
```
network:
  ethernets:
    enp6s16:
      dhcp4: no
    enp6s17:
      dhcp4: no
  bridges:
    br0:
      interfaces: [enp6s16]
      addresses: [192.168.81.10/24]
      dhcp4: no
      dhcp6: no
    br1:
      interfaces: [enp6s17]
      addresses: [192.168.82.10/24]
      dhcp4: no
      dhcp6: no
  version: 2
```

Docker：27.3.1
docker run -itd --net=none --name ub1 ubuntu:20.04 /bin/bash
pipework br0 ub1 192.168.81.200/24

docker run -itd --net=none --name ub2 ubuntu:20.04 /bin/bash
pipework br1 ub2 192.168.82.200/24

---

VirtualPC
192.168.81.10 -> 192.168.81.200 OK
192.168.82.10 -> 192.168.82.200 OK

OtherPC
192.168.81.20 -> 192.168.81.10 OK
192.168.82.20 -> 192.168.82.10 OK
192.168.81.20 -> 192.168.81.200 Error
192.168.82.20 -> 192.168.82.200 Error
